### ISSUE TITLE
xandikos support?

### ISSUE THREAD

**Issue by alex3kov** [BlackIkeEagle/muttvcardsearch#11]
Hi,
I have a xandikos server behind nginx (for authentication).
```
$ muttvcardsearch --create-local-cache
Creating cache entries for config section [xand_personal], URL: [http://192.168.2.1:8099/usr/contacts/personal]
Export failed, nothing found
```
vdirsyncer and DavX5 sync fine with it. Here are the server logs for `vdirsyncer sync` and `muttvcardsearch --create-local-cache`:
```
Jan 03 23:43:31 homepc xandikos[103051]: INFO:aiohttp.access: [03/Jan/2022:20:43:31 +0000] "PROPFIND /usr/contacts/personal/ HTTP/1.0" 207 8515 "-" "vdirsyncer/0.18.1.dev0+g3191886.d20211231"
Jan 03 23:44:13 homepc xandikos[103051]: INFO:aiohttp.access: [03/Jan/2022:20:44:13 +0000] "PROPFIND /usr/contacts/personal/ HTTP/1.0" 207 9311 "-" "-"
```
Config:
```
[xand_personal]
password=XXXXX
server=http://192.168.2.1:8099/usr/contacts/personal/
username=usr
```

**Comment by tfl** [comment]
See my fork at https://github.com/tfl/muttvcardsearch. I set up a Xandikos server and added a new contact using Thunderbird (Cardbook plugin). I was able to pull out that contact and put it into the cache. Mutt was then able to use that contact. Hope that helps. Note: your URL should look like this: `http://localhost:8080/user/contacts/addressbook` (or whatever hostname and port you use) not `.../usr/contacts/personal`

**Comment by alex3kov** [comment]
> See my fork at https://github.com/tfl/muttvcardsearch

Thanks, I'll try it

> your URL should look like this: http://localhost:8080/user/contacts/addressbook (or whatever hostname and port you use) not .../usr/contacts/personal

No it shouldn't. I know what principal/collections I'm using in my Xandikos instance :)

> By using curl you should be able to basically test your setup: `curl -X PROPFIND -u user:pass http://192.168.2.1:8099/usr/contacts/personal

It works on 2.7.0 from this repo (didn't try yours yet) - lists all the UUIDs and stuff:
```
<ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:carddav" xmlns:ns2="http://calendarserver.org/ns/" xmlns:ns3="http://apache.org/dav/props/"><ns0:response><ns0:href>/usr/contacts/personal/</ns0:href><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /><ns1:addressbook /></ns0:resourcetype><ns0:current-user-principal><ns0:href>/usr/</ns0:href></ns0:current-user-principal><ns0:displayname>personal</ns0:displayname><ns0:getetag>"450b7f1e8fb3d1abe6814379b583bcfd31e6b861"</ns0:getetag><ns0:getcontenttype>httpd/unix-directory</ns0:getcontenttype><ns1:addressbook-description /><ns2:getctag>450b7f1e8fb3d1abe6814379b583bcfd31e6b861</ns2:getctag><ns0:getctag>450b7f1e8fb3d1abe6814379b583bcfd31e6b861</ns0:getctag>
```

**Comment by tfl** [comment]
Since there is no response I close this issue. The project seem to be abandoned.
