### ISSUE TITLE
transfer repo ?

### ISSUE THREAD

**Issue by BlackIkeEagle** [BlackIkeEagle/muttvcardsearch#9]
Since you are abbandoning the project, are you willing to transfer the repo to me ?

I'll gladly keep it alive and maybe add more features on the go.

Thanks for creating this tool, I'm using it almost daily.

**Comment by tfl** [comment]
I'm sorry not to respond to you. I simply did not see your question.
I am happy to see that somebody will take over my project and keep it alive.
What do I have to do?

**Comment by tfl** [comment]
If you still like to take over the project just drop me a note

**Comment by BlackIkeEagle** [comment]
yes I'm still interested.

to transfer it, you can go via 'settings' and then 'transfer ownership'

By default you retain your push rights and I have no intention to remove those.

**Comment by tfl** [comment]
Github wont let me transfer the repository untill the recipient has one with the same name. Maybe you have to rename your fork?

**Comment by BlackIkeEagle** [comment]
hmm it was renamed, but I just deleted my fork now. Could you try again ?

**Comment by tfl** [comment]
Looks good now. Github responds: "Repository transfer to BlackIkeEagle requested"

**Comment by BlackIkeEagle** [comment]
Jep success, thanks.
